server:
  port: 8088
  
spring:
  application:
    name: course-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/db_course?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password:
    
  jpa: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection: 
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true 
    hibernate:
      ddl-auto: none
